version: "3"

networks:
  monreseau:
    external: false

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      DATABASE_URL: postgres://strat:admin@localhost:5432/postgres
      POSTGRES_USER: strat
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: strat-api
    volumes:
      - pgbd:/var/lib/postgresql/data
    networks:
      - monreseau


  strat-api:
    image: strat-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strat-api
    volumes:
      - pokemons:/app/pokemons
      - equipes:/app/equipes
      - .:/app
    networks:
      - monreseau
    ports:
      - "3000:3000"

volumes:
  pgbd:
  pokemons:
  equipes:
