FROM node:18-alpine
ENV NODE_ENV production
WORKDIR /app
COPY package.json yarn.lock ./  
COPY . .
RUN yarn --frozen-lockfile --production 
RUN yarn build
CMD ["yarn", "start", "start:prod"]
EXPOSE 3300