/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ILsMegiq1c4nbXYHOfwJmMVwUDh+oMKrKmtqDOrZ0Fq7FqLvuc46cpMRvGIkdBHpJ2U7rTg/6mkKt6vw23b2bQ==
 */

/* eslint-disable */
// tslint:disable

import Pokemons, {Pokemons_InsertParameters} from './pokemons'

interface DatabaseSchema {
  pokemons: {record: Pokemons, insert: Pokemons_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  Pokemons,
  Pokemons_InsertParameters,
}
