name: Docker Push

on:
  push:
    branches: [ "main" ]

jobs:
  build-run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Api container
        run: docker build -t strat-api .
      - name: Build DB container
        run: docker build -t postgres .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: cloudblip06
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Push Api Docker image
        run: |
         docker images
         docker tag strat-api cloudblip06/strat-api
         docker push cloudblip06/strat-api  
      - name: Push Api Docker image
        run: |
         docker images
         docker tag postgres:latest cloudblip06/postgres
         docker push cloudblip06/postgres  
      - name: Stop the API
        run: docker-compose down
      