name: Docker Build and Push

on:
  push:
    branches: [ "main" ]

jobs:
  build-run-tests:
    runs-on: node:18-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Build and run the API
        run: docker-compose up -d strat-api
      - name: Wait for the API to start
        run: sleep 5
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: cloudblip06
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Push Docker image
        run: |
         docker tag strat-api cloudblip06/strat-api
         docker push cloudblip06/strat-api  
      - name: Stop the API
        run: docker-compose down
      