name: Deploy from production

on:
  push:
    branches: ["main"]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  pull_and_deploy:
    runs-on: ubuntu-latest

    needs: [prepare, build-and-push]  # depends on Docker push Workflow

    steps:
      - name: Running prod services
        run: docker compose -f docker-compose.prod.yml up -d
      - name: Stoping services
        run: docker compose -f docker-compose.prod.yml down