name: Deploy from production

on:
  workflow_run:
    workflows: ["Docker Push"]
    branches: ["main"]
    types:
      - completed

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  pull_and_deploy:
    runs-on: ubuntu-latest

    needs: [prepare, Docker Push]
    steps:
      - name: Running prod services
        run: docker-compose -f docker-compose.prod.yml up -d
      - name: Stoping services
        run: docker-compose -f docker-compose.prod.yml down
