name: Docker Test

on:
  push:
    branches: [ "main" ]

jobs:
  
    build:
  
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t strat-api .
      - name: Run the Docker image
        run: docker compose up -d


      - name: Wait for the API to start
        run: sleep 10
      - name: Run the tests
        run: docker compose exec strat-api yarn test
      - name: Stop the Docker image
        run: docker compose down