name: Run all tests

on:
  push:
    branches: [ "api-dev" ]


jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Execute tests
        run: yarn && yarn test